window._ASP_load=function(){let f=WPD.dom;window.ASP.instances={instances:[],get:function(c,b){this.clean();if("undefined"===typeof c||0==c)return this.instances;if("undefined"===typeof b){b=[];for(var a=0;a<this.instances.length;a++)this.instances[a].o.id==c&&b.push(this.instances[a]);return 0<b.length?b:!1}for(a=0;a<this.instances.length;a++)if(this.instances[a].o.id==c&&this.instances[a].o.iid==b)return this.instances[a];return!1},set:function(c){if(this.exist(c.o.id,c.o.iid))return!1;this.instances.push(c);
return!0},exist:function(c,b){this.clean();for(let a=0;a<this.instances.length;a++)if(this.instances[a].o.id==c&&("undefined"===typeof b||this.instances[a].o.iid==b))return!0;return!1},clean:function(){let c=[],b=this;this.instances.forEach(function(a,d){0==f(".asp_m_"+a.o.rid).length&&c.push(d)});c.forEach(function(a){"undefined"!==typeof b.instances[a]&&(b.instances[a].destroy(),b.instances.splice(a,1))})},destroy:function(c,b){let a=this.get(c,b);if(!1!==a)if(Array.isArray(a))a.forEach(function(d){d.destroy()}),
this.instances=[];else{let d=0;this.instances.forEach(function(e,g){e.o.id==c&&e.o.iid==b&&(d=g)});a.destroy();this.instances.splice(d,1)}}};window.ASP.initialized=!1;window.ASP.initializeById=function(c,b){let a=".asp_init_data";b="undefined"==typeof b?!1:b;"undefined"!==typeof c&&"object"!=typeof c&&(a="div[id*=asp_init_id_"+c+"]");let d=0;f(a).forEach(function(e){let g=f(e).closest(".asp_w_container").find(".asp_m");if(0==g.length||"undefined"!=typeof g.get(0).hasAsp)return++d,!0;if(!b&&!g.inViewPort(-100))return!0;
e=f(e).data("aspdata");if("undefined"===typeof e)return!0;e=WPD.Base64.decode(e);if("undefined"===typeof e||""==e)return!0;e=JSON.parse(e);g.get(0).hasAsp=!0;++d;return g.ajaxsearchpro(e)});f(a).length==d&&(document.removeEventListener("scroll",ASP.initializeById),document.removeEventListener("resize",ASP.initializeById))};window.ASP.initialize=function(c){if("undefined"==typeof this.version)return!1;ASP.script_async_load?(document.addEventListener("scroll",ASP.initializeById,{passive:!0}),document.addEventListener("resize",
ASP.initializeById,{passive:!0}),ASP.initializeById(c),setTimeout(function(){ASP.initializeById(c,!0)},4E3)):ASP.initializeById(c,!0);if(this.highlight.enabled){let b=localStorage.getItem("asp_phrase_highlight");localStorage.removeItem("asp_phrase_highlight");null!=b&&(b=JSON.parse(b),this.highlight.data.forEach(function(a){if(a.id==b.id){var d=""!=a.selector&&0<f(a.selector).length?a.selector:"article";d=0<f(d).length?d:"body";f(d).highlight(b.phrase,{element:"span",className:"asp_single_highlighted_"+
b.id,wordsOnly:a.whole,excludeParents:".asp_w, .asp-try"});d=f(".asp_single_highlighted_"+b.id);if(a.scroll&&0<d.length){d=d.offset().top-120;let e=f("#wpadminbar");0<e.length&&(d-=e.height());d+=a.scroll_offset;d=0>d?0:d;f("html").animate({scrollTop:d},500)}return!1}}))}this.initialized=!0};window.ASP.ready=function(){let c=this,b=f("body"),a,d,e;c.initialize();if("undefined"!=typeof ASP.detect_ajax&&1==ASP.detect_ajax){let g=new MutationObserver(function(){clearTimeout(a);a=setTimeout(function(){c.initialize()},
500)});function h(){let k=document.querySelector("body");k?g.observe(k,{subtree:!0,childList:!0}):window.setTimeout(h,500)}h()}f(window).on("resize",function(){clearTimeout(d);d=setTimeout(function(){c.initializeById()},200)});b.on("click touchend","#menu-item-search, .fa-search, .fa, .fas, .fusion-flyout-menu-toggle, .fusion-main-menu-search-open, #search_button, .mini-search.popup-search, .icon-search, .menu-item-search-dropdown, .mobile-menu-button, .td-icon-search, .tdb-search-icon, .side_menu_button, .search_button, .raven-search-form-toggle, [data-elementor-open-lightbox], .elementor-button-link, .elementor-button, i[class*=-search], a[class*=-search]",
function(){clearTimeout(e);e=setTimeout(function(){c.initializeById({},!0)},300)});if("undefined"!=typeof jQuery)jQuery(document).on("elementor/popup/show",function(){setTimeout(function(){c.initializeById({},!0)},10)})};window.ASP.loadScriptStack=function(c){let b;0<c.length&&(b=document.createElement("script"),b.src=c.shift().src,b.onload=function(){0<c.length?window.ASP.loadScriptStack(c):window.ASP.ready()},document.body.appendChild(b))};window.ASP.init=function(){ASP.script_async_load?window.ASP.loadScriptStack(ASP.additional_scripts):
"undefined"!==typeof WPD.ajaxsearchpro&&window.ASP.ready()};window.ASP.css_async&&"undefined"==typeof window.ASP.css_loaded||window.WPD.intervalUntilExecute(window.ASP.init,function(){return"undefined"!=typeof window.ASP.version&&"undefined"!=f.fn.ajaxsearchpro})};(function(){"undefined"!=typeof WPD&&"undefined"!=typeof WPD.dom?window._ASP_load():document.addEventListener("wpd-dom-core-loaded",window._ASP_load)})();
